parku/docs

_includes/partials/nav.html
api/payment.md
changelog.md

I messed up this branch. Just see `api/payment.md`.

Remove currency parameter

---

_includes/partials/nav.html
changelog.md

I messed up this branch. Just see `changelog.md`.

Add changelog file.

---

_includes/partials/nav.html
_layouts/default.html
changelog.md

I messed up this branch. Just see `_layouts/default.html` for changes.

Google Analytics

---

api/boxes.md
changelog.md

Feedback about language and understanding is appreciated.

New endpoint: `/boxes`

---

api/bookings.md
api/locations.md

I am unsure about the name `open_order`. Maybe someone has a nicer name.

SYS-867 adding the opening order property

---

api/user.md

so spa can post facebook_id to /v4/user as in sys-855

SYS-855 Added facebook_id parameter to User

---

api/locations.md
changelog.md

I added minimum_displayprice_unit and minimum_displayprice to location endpoint.

SYS-746 New fields for location endpoint

---

api/user.md
changelog.md

'Cars' and 'phone_numbers' can now be send to user endpoint when creating a new user.

SYS-884 Added `cars` and `phone_numbers` to user endpoint

---

api/bookings.md
changelog.md

When you retrieve a booking the post booking information is sent with the response

SYS-877 Add post booking information to bookings

---

api/user.md

Posting `attributes` to /v4/user is now possible, thereby adding UserAttributes to the user. They may also be updated.

SYS-906 Added attributes to User endpoint

---

api/locations.md
changelog.md

SYS-981 remove minimum_displayprice* and added price_unit

---

api/attributes.md
api/user.md

UserAttributes are now handled differently. This PR reflects these changes.

SYS-931 Modified docs for Attributes

---

api/bookings.md
api/locations.md
changelog.md

Reverts parku/docs#37
Clicked merge too soon, this is not implemented yet.

Revert "SYS-1060 Added settings to location"

---

api/settings.md
changelog.md

SYS-1073 expose sesam settings

---

Gemfile.lock
api/coupon.md
changelog.md

This Pull Requests adds everything about the coupon endpoint into the API documentation.

DEV-169 Coupon endpoint

---

api/locations.md

Forgot to add an empty line before notes started, added some highlighting.

DEV-282 Add empty line before notes

---

api/bookings.md
api/locations.md

Well... should be obvious, i hope i did not forget a point where to add the documentation about the pricing.

DEV-448 Add pricing doc for bookings and locations

---

Gemfile.lock
_includes/assets/css/shared/markdown.css
api/locations.md

This pull request contains the next_available_slot, current, maximum and availability changes introduced with version 4 of the apps.
I also updated the underlying infrastructure a bit and changed table borders to be visible for a better overview in long tables.

DEV-640 Refactored locations api description

---

api/locations.md

Adds the bookability field to the api documentation and does some minor fixes.

Dev 754 bookability field

---

v5/bookings.apib

Even docs for fuckin ford flag

DEV-2094 Added ford device flag
